version: '3'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server

  cache-service:
    build: ./cache-service
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka-server
