spring:
  application:
    name: cache-service
  config:
    import: "optional:configserver:http://localhost:8881"
  cloud:
    config:
      uri: http://localhost:8881

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/