name: Cache Service CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install -X

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          cd cache-service
          docker build -t $DOCKERHUB_USERNAME/cache-service:${{ github.sha }} .
          docker push $DOCKERHUB_USERNAME/cache-service:${{ github.sha }}

      - name: Deploy to EC2
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ec2-user
        run: |
          echo "$EC2_SSH_PRIVATE_KEY" > EC2_key.pem
          chmod 600 EC2_key.pem
          ssh -o StrictHostKeyChecking=no -i EC2_key.pem ${EC2_USER}@${EC2_HOST} '
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cache-service:${{ github.sha }}
            docker stop cache-service || true
            docker rm cache-service || true
            docker run -d --name cache-service -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/cache-service:${{ github.sha }}
          '
          rm EC2_key.pem